name: coverage

on: [push, pull_request]

jobs:
  macos:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    strategy:
      matrix:
        r: [latest]
        # r: [3.5, 3.6, devel]
    runs-on: macOS-latest
    env:
      NOT_CRAN: true
      R_LANGSVR_LOG: /tmp/languageserver/log
      R_LANGSVR_POOL_SIZE: 1
      R_LANGSVR_TEST_FAST: NO
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r }}
    - name: Install languagesever
      run: |
        Rscript -e "install.packages(c('remotes'), repos = 'https://cloud.r-project.org')"
        Rscript -e "remotes::install_deps(dependencies = TRUE)"
        Rscript -e "remotes::install_local()"
    - name: Covr (to be removed)
      id: package_coverage
      continue-on-error: true
      run: |
        mkdir -p /tmp/languageserver
        Rscript -e "cat(paste0('::set-output ', 'name=COVRTD::', tempdir(), '\n'))" -e "covr::package_coverage(quiet = FALSE, clean = FALSE)"
    - uses: actions/upload-artifact@v1
      if: steps.package_coverage.conclusion == 'failure'
      with:
        name: macos-log
        path: ${{ steps.package_coverage.outputs.COVRTD }}
    - uses: actions/upload-artifact@v1
      if: steps.package_coverage.conclusion == 'failure'
      with:
        name: macos-log
        path: /tmp/languageserver
    # - name: Codecov
    #   run: Rscript -e "covr::codecov(quiet = FALSE)"
    #   env:
    #     CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
